# Generated by Django 3.0.7 on 2020-08-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200810_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personelaccount',
            name='location',
        ),
        migrations.RemoveField(
            model_name='restaurantaccount',
            name='location',
        ),
    ]
