# Generated by Django 3.0.7 on 2020-08-10 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200810_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='personelaccount',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Locations_person', to='accounts.PersonLocations'),
        ),
        migrations.AddField(
            model_name='restaurantaccount',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Locations_restaurants', to='accounts.RestaurantLocations'),
        ),
    ]
