# Generated by Django 3.0.7 on 2020-08-11 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200811_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personlocations',
            name='added_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.PersonelAccount'),
        ),
        migrations.AlterField(
            model_name='restaurantlocations',
            name='added_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.RestaurantAccount'),
        ),
    ]
