# Generated by Django 3.0.7 on 2020-08-13 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_restaurantaccount_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantaccount',
            old_name='points',
            new_name='score',
        ),
    ]
