# Generated by Django 3.0.7 on 2020-08-13 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200814_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rst', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.RestaurantAccount')),
            ],
        ),
    ]
