# Generated by Django 3.0.7 on 2020-08-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='ispromoted',
            field=models.BooleanField(default=False),
        ),
    ]
