# Generated by Django 3.0.7 on 2020-08-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_ordered_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_type',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('SUBMITED', 'SUBMITED'), ('CONFIRMED', 'CONFIRMED'), ('READY', 'READY'), ('DELEVERED', 'DELEVERED'), ('CANCLED', 'CANCLED'), ('FINISHED', 'FINISHED')], max_length=100),
        ),
    ]
