# Generated by Django 3.0.7 on 2020-08-05 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0006_auto_20200805_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='ordered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ordered_by_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.PersonelAccount'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ordered_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.RestaurantAccount'),
        ),
    ]
