# Generated by Django 3.0.7 on 2020-08-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200805_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('SUBMITED', 'SUBMITED'), ('CONFIRMED', 'CONFIRMED'), ('READY', 'READY'), ('DELIVERED', 'DELIVERED'), ('CANCLED', 'CANCLED'), ('FINISHED', 'FINISHED')], max_length=50),
        ),
    ]
